import sys
binary = bin(int(*sys.argv[1:2]))
binary01 = binary.replace("0b", "")
print(binary01)
octal = oct(int(*sys.argv[1:2]))
octal01 = octal.replace("0o", "")
print(octal01)
hexa = hex(int(*sys.argv[1:2]))
hexa01 = hexa.replace("0x", "")
print(hexa01)